spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    command:
      completion:
        root-command: spring-up
      version:
        show-git-short-commit-id: true
  up:
    templateCatalogs:
      - name: catalog1
        description: The first catalog
        url: https://github.com/rd-1-2022/template-catalog
      - name: catalog2
        description: The second catalog
        url: https://github.com/rd-1-2022/template-catalog-2
    templateRepositories:
      - name: jpa
        description: Learn how to work with JPA data persistence using Spring Data JPA.
        url: https://github.com/rd-1-2022/rpt-spring-data-jpa
        tags:
          - jpa
          - h2
    defaults:
      packageName: com.xkcd
      templateRepositoryName: jpa
## disable console logging
logging:
#  pattern:
#    console:
# log debug from a cli
  file:
    name: shell.log
  level:
    root: debug
    org:
      springframework:
        experimental:
          up: debug
        shell: debug
